### ISSUE TITLE
chyba AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by hanecak** [soit-sk/zmluvy_bratislava#2]
Aktualne scraper po stiahnuti cca š poloziek skonci s chybou:

``````
Injecting configuration and compiling...
Injecting scraper and running...
INFO: Requesting content from url: "http://www.bratislava.sk/register/vismo/zobraz_dok.asp?id_org=700026&stranka=1&tzv=1&pocet=10&sz=zmena_formalni&sz=nazev&sz=strvlastnik&sort=zmena_formalni&sc=DESC"
INFO: Starting new HTTP connection (1): www.bratislava.sk
INFO: Requesting content from url: "http://www.bratislava.sk/register/vismo/dokumenty2.asp?id_org=700026&id=35818&p1=15331"
INFO: Starting new HTTP connection (1): www.bratislava.sk
INFO: Requesting content from url: "http://www.bratislava.sk/register/vismo/o_osoba.asp?id_org=700026&id_o=1061"
INFO: Starting new HTTP connection (1): www.bratislava.sk
INFO: Requesting content from url: "http://www.bratislava.sk/register/vismo/dokumenty2.asp?id_org=700026&id=35816&p1=15331"
INFO: Starting new HTTP connection (1): www.bratislava.sk
INFO: Requesting content from url: "http://www.bratislava.sk/register/vismo/o_osoba.asp?id_org=700026&id_o=1095"
INFO: Starting new HTTP connection (1): www.bratislava.sk
Traceback (most recent call last):
  File "scraper.py", line 283, in <module>
    scraper.scrape()
  File "scraper.py", line 91, in scrape
    if self.parse_list(content) is None:
  File "scraper.py", line 124, in parse_list
    row['responsible_person'] = self.scrape_person(cells[2].a)
  File "scraper.py", line 267, in scrape_person
    person['email'] = self.parse_person_email(content)
  File "scraper.py", line 61, in parse_person_email
    for dd in dl.find_all('dd'):
AttributeError: 'NoneType' object has no attribute 'find_all'```
``````

**Comment by ricco386** [comment]
momentlane scraper bezi, zda sa ze problem moze byt v roznych formatoch (pridali data a error sa posunul dakam kam sa scraper este nedostane). Napr. scrape_person predpoklada ze v bunke bude a tag ale nie vzdy tam je. Nefixol som kedze sa mi nepodarilo zreprodukovat, ale v buducnosti sa moze objavit (a aj objavi) opat.
