### ISSUE TITLE
Missing section error

### ISSUE THREAD

**Issue by ricco386** [soit-sk/zmluvy_bratislava#4]
``` python
Traceback (most recent call last):
  File "scraper.py", line 360, in <module>
    scraper.scrape()
  File "scraper.py", line 149, in scrape
    if self.parse_list(content) is None:
  File "scraper.py", line 184, in parse_list
    row['responsible_person'] = self.scrape_person(cells[2].a)
  File "scraper.py", line 343, in scrape_person
    person.update(self.parse_person_contact_details(content))
  File "scraper.py", line 68, in parse_person_contact_details
    section['id'] = int(params['id_u'][0])
KeyError: 'id_u'
```

**Comment by ricco386** [comment]
fixed in commit: 849fb1c73c23cfd8667faf7e86e69c69a130352b
